"""Write the profile tables and generate docs/data_profile.md from them."""

from pathlib import Path
from typing import Any

import pandas as pd

from cigd.config import REPOSITORY_ROOT, StudyConfig
from cigd.ingest.eia import read_eia_prices
from cigd.ingest.nyserda import read_price_panel
from cigd.ingest.open_meteo import read_weather
from cigd.logging import get_logger
from cigd.profiling.prices import (
    crosscheck_with_eia,
    list_missing_weeks,
    list_price_outliers,
    profile_price_series,
)
from cigd.profiling.trips import describe_schema_changes, profile_trip_months, profile_trip_schema
from cigd.profiling.weather import profile_weather

logger = get_logger(__name__)

# Long tables are shown in full in their CSV; the document shows the first rows.
MAX_ROWS_IN_DOCUMENT = 25


def markdown_table(table: pd.DataFrame) -> str:
    """Render a small DataFrame as a GitHub Markdown table."""
    shown = table.head(MAX_ROWS_IN_DOCUMENT)
    header = "| " + " | ".join(str(column) for column in shown.columns) + " |"
    divider = "|" + "---|" * len(shown.columns)
    body = ["| " + " | ".join(str(value) for value in row) + " |" for row in shown.to_numpy()]
    lines = [header, divider, *body]
    if len(table) > len(shown):
        lines.append(f"\nShowing {len(shown)} of {len(table)} rows; see the CSV for all of them.")
    return "\n".join(lines)


def summarise_sources(
    trip_months: pd.DataFrame,
    price_series: pd.DataFrame,
    eia_prices: pd.DataFrame,
    weather: pd.DataFrame,
) -> pd.DataFrame:
    """Return one line per source with its size and time span."""
    return pd.DataFrame(
        [
            {
                "source": "yellow_taxi",
                "grain": "one trip",
                "units": f"{len(trip_months)} monthly files",
                "rows": int(trip_months["trip_rows"].sum()),
                "first": trip_months["first_pickup"].min(),
                "last": trip_months["last_pickup"].max(),
            },
            {
                "source": "nyserda_gasoline",
                "grain": "one series per week",
                "units": f"{len(price_series)} series",
                "rows": int(price_series["weeks_with_price"].sum()),
                "first": price_series["first_priced_week"].min(),
                "last": price_series["last_priced_week"].max(),
            },
            {
                "source": "eia_gasoline",
                "grain": "one series per week",
                "units": f"{eia_prices['series_id'].nunique()} series",
                "rows": len(eia_prices),
                "first": eia_prices["week_start"].min().date(),
                "last": eia_prices["week_start"].max().date(),
            },
            {
                "source": "open_meteo",
                "grain": "one region per day",
                "units": f"{weather['region_code'].nunique()} regions",
                "rows": len(weather),
                "first": weather["weather_date"].min().date(),
                "last": weather["weather_date"].max().date(),
            },
        ]
    )


def profile_document_path(config: StudyConfig) -> Path:
    """Return where the generated profile document goes; smoke runs never touch docs/."""
    if config.profile == "full":
        return REPOSITORY_ROOT / "docs" / "data_profile.md"
    return config.results_dir / "data_profile.md"


def write_profile_document(config: StudyConfig, tables: dict[str, pd.DataFrame]) -> Path:
    """Write the Markdown data profile from the profile tables."""
    crosscheck = tables["eia_crosscheck"]
    tested = crosscheck[crosscheck["held_to_tolerance"]].iloc[0]
    tolerance = config.quality["eia_crosscheck"]
    verdict = "PASSED" if tested["within_tolerance"] else "FAILED"
    sections = [
        "# Data profile",
        f"Generated by `python -m cigd --profile {config.profile} profile` from the files "
        f"in `provenance/manifest.csv` (config hash `{config.config_hash}`, data cutoff "
        f"{config.data_cutoff_date}). Do not edit by hand; every table below is also "
        "written to `results/tables/profile_*.csv`.",
        "## Sources",
        markdown_table(tables["sources"]),
        "## Yellow taxi trips",
        "Counts are taken from the files as published, before any cleaning.",
        markdown_table(tables["trip_months"]),
        "### Schema changes between consecutive months",
        markdown_table(tables["trip_schema_changes"]),
        "## NYSERDA weekly price panel",
        markdown_table(tables["price_series"]),
        "### Weeks without a price",
        markdown_table(tables["price_missing_weeks"]),
        "### Flagged prices (kept, not removed)",
        markdown_table(tables["price_outliers"]),
        "## EIA cross-check",
        f"Tolerance, fixed before profiling: median absolute difference at most "
        f"{tolerance['max_median_absolute_difference_usd']} USD per gallon and correlation at "
        f"least {tolerance['min_correlation']}, for the NYSERDA state average against EIA New "
        f"York State on the same Monday (offset 0). Result: **{verdict}**.",
        markdown_table(crosscheck),
        "## Weather",
        markdown_table(tables["weather"]),
    ]
    document_path = profile_document_path(config)
    document_path.parent.mkdir(parents=True, exist_ok=True)
    document_path.write_text("\n\n".join(sections) + "\n", encoding="utf-8", newline="\n")
    return document_path


def run_profile(config: StudyConfig) -> dict[str, Any]:
    """Profile every source, write the tables and the document, and return a summary."""
    panel = read_price_panel(config)
    eia_prices = read_eia_prices(config)
    weather = read_weather(config)
    trip_months = profile_trip_months(config)
    trip_schema = profile_trip_schema(config)

    tables = {
        "trip_months": trip_months,
        "trip_schema": trip_schema,
        "trip_schema_changes": describe_schema_changes(trip_schema),
        "price_series": profile_price_series(panel, config),
        "price_missing_weeks": list_missing_weeks(panel, config),
        "price_outliers": list_price_outliers(panel, config),
        "eia_crosscheck": crosscheck_with_eia(panel, eia_prices, config),
        "weather": profile_weather(weather),
    }
    tables["sources"] = summarise_sources(trip_months, tables["price_series"], eia_prices, weather)

    config.tables_dir.mkdir(parents=True, exist_ok=True)
    for table_name, table in tables.items():
        table.to_csv(
            config.tables_dir / f"profile_{table_name}.csv", index=False, lineterminator="\n"
        )
    document_path = write_profile_document(config, tables)
    logger.info("data profile written to %s", document_path)

    crosscheck = tables["eia_crosscheck"]
    tested = crosscheck[crosscheck["held_to_tolerance"]].iloc[0]
    return {
        "trip_rows": int(trip_months["trip_rows"].sum()),
        "price_series": len(tables["price_series"]),
        "missing_series_weeks": len(tables["price_missing_weeks"]),
        "flagged_prices": len(tables["price_outliers"]),
        "eia_crosscheck": "passed" if tested["within_tolerance"] else "failed",
    }
